--
-- PostgreSQL database dump
--

\restrict ZE4R1WTCt2TkQi18qIldI2hSW9z5pTRLEjzyPxoOBm0tXGx7b3Zv2cAFV7HBcnV

-- Dumped from database version 14.19 (Homebrew)
-- Dumped by pg_dump version 14.19 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_activity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_activity (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    quarter character varying(2) NOT NULL,
    year integer NOT NULL,
    date_label character varying(50) NOT NULL,
    status character varying(15) NOT NULL,
    "order" integer NOT NULL,
    CONSTRAINT core_activity_order_check CHECK (("order" >= 0)),
    CONSTRAINT core_activity_year_check CHECK ((year >= 0))
);


ALTER TABLE public.core_activity OWNER TO postgres;

--
-- Name: core_activity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_associationinfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_associationinfo (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    full_name character varying(300) NOT NULL,
    slogan character varying(300) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(20) NOT NULL,
    address text NOT NULL,
    facebook_url character varying(200) NOT NULL,
    linkedin_url character varying(200) NOT NULL,
    adhesion_fee integer NOT NULL,
    monthly_fee integer NOT NULL,
    annual_fee integer NOT NULL,
    whatsapp character varying(20) NOT NULL,
    CONSTRAINT core_associationinfo_adhesion_fee_check CHECK ((adhesion_fee >= 0)),
    CONSTRAINT core_associationinfo_annual_fee_check CHECK ((annual_fee >= 0)),
    CONSTRAINT core_associationinfo_monthly_fee_check CHECK ((monthly_fee >= 0))
);


ALTER TABLE public.core_associationinfo OWNER TO postgres;

--
-- Name: core_associationinfo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_associationinfo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_associationinfo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_bureaumember; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_bureaumember (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    role character varying(200) NOT NULL,
    category character varying(20) NOT NULL,
    photo character varying(100) NOT NULL,
    "order" integer NOT NULL,
    member_id bigint,
    CONSTRAINT core_bureaumember_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.core_bureaumember OWNER TO postgres;

--
-- Name: core_bureaumember_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_bureaumember ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_bureaumember_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_contactmessage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_contactmessage (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    email character varying(254) NOT NULL,
    subject character varying(200) NOT NULL,
    message text NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_contactmessage OWNER TO postgres;

--
-- Name: core_contactmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_contactmessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_contactmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_cotisationpayment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_cotisationpayment (
    id bigint NOT NULL,
    amount integer NOT NULL,
    period_label character varying(50) NOT NULL,
    payment_method character varying(50) NOT NULL,
    reference character varying(100) NOT NULL,
    paid_at date NOT NULL,
    created_at timestamp with time zone NOT NULL,
    member_id bigint NOT NULL,
    CONSTRAINT core_cotisationpayment_amount_check CHECK ((amount >= 0))
);


ALTER TABLE public.core_cotisationpayment OWNER TO postgres;

--
-- Name: core_cotisationpayment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_cotisationpayment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_cotisationpayment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_event; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_event (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    date timestamp with time zone NOT NULL,
    location character varying(200) NOT NULL,
    image character varying(100) NOT NULL,
    is_published boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    category character varying(20) NOT NULL,
    is_featured boolean NOT NULL
);


ALTER TABLE public.core_event OWNER TO postgres;

--
-- Name: core_event_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_faq; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_faq (
    id bigint NOT NULL,
    question character varying(300) NOT NULL,
    answer text NOT NULL,
    "order" integer NOT NULL,
    is_published boolean NOT NULL,
    CONSTRAINT core_faq_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.core_faq OWNER TO postgres;

--
-- Name: core_faq_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_faq ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_faq_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_galleryalbum; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_galleryalbum (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    cover_image character varying(100) NOT NULL,
    is_published boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    event_id bigint
);


ALTER TABLE public.core_galleryalbum OWNER TO postgres;

--
-- Name: core_galleryalbum_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_galleryalbum ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_galleryalbum_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_galleryimage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_galleryimage (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    image character varying(100) NOT NULL,
    caption text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    event_id bigint,
    album_id bigint
);


ALTER TABLE public.core_galleryimage OWNER TO postgres;

--
-- Name: core_galleryimage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_galleryimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_galleryimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_joboffer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_joboffer (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    company character varying(200) NOT NULL,
    location character varying(200) NOT NULL,
    job_type character varying(10) NOT NULL,
    sector character varying(100) NOT NULL,
    description text NOT NULL,
    apply_url character varying(200) NOT NULL,
    poster_name character varying(200) NOT NULL,
    poster_email character varying(254) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    posted_by_id bigint
);


ALTER TABLE public.core_joboffer OWNER TO postgres;

--
-- Name: core_joboffer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_joboffer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_joboffer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_member; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_member (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    phone character varying(20) NOT NULL,
    promotion_id bigint,
    profession character varying(200) NOT NULL,
    company character varying(200) NOT NULL,
    city character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    bio text NOT NULL,
    photo character varying(100) NOT NULL,
    linkedin character varying(200) NOT NULL,
    is_approved boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    cotisation_mode character varying(10) NOT NULL,
    membership_type character varying(10) NOT NULL,
    member_number character varying(20)
);


ALTER TABLE public.core_member OWNER TO postgres;

--
-- Name: core_member_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_member_groups (
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.core_member_groups OWNER TO postgres;

--
-- Name: core_member_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_member_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_member_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_member_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_member_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_member_user_permissions (
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.core_member_user_permissions OWNER TO postgres;

--
-- Name: core_member_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_member_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_member_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_memberdocument; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_memberdocument (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    category character varying(20) NOT NULL,
    file character varying(100) NOT NULL,
    description text NOT NULL,
    is_adherent_only boolean NOT NULL,
    published_at date NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_memberdocument OWNER TO postgres;

--
-- Name: core_memberdocument_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_memberdocument ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_memberdocument_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_newsarticle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_newsarticle (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    slug character varying(50) NOT NULL,
    excerpt text NOT NULL,
    content text NOT NULL,
    image character varying(100) NOT NULL,
    is_published boolean NOT NULL,
    published_at timestamp with time zone NOT NULL,
    author_id bigint
);


ALTER TABLE public.core_newsarticle OWNER TO postgres;

--
-- Name: core_newsarticle_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_newsarticle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_newsarticle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_newslettersubscriber; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_newslettersubscriber (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    is_active boolean NOT NULL,
    subscribed_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_newslettersubscriber OWNER TO postgres;

--
-- Name: core_newslettersubscriber_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_newslettersubscriber ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_newslettersubscriber_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_notification (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    message text NOT NULL,
    notification_type character varying(15) NOT NULL,
    is_read boolean NOT NULL,
    link character varying(300) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    recipient_id bigint NOT NULL
);


ALTER TABLE public.core_notification OWNER TO postgres;

--
-- Name: core_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_partner; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_partner (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    logo character varying(100) NOT NULL,
    website character varying(200) NOT NULL,
    "order" integer NOT NULL,
    CONSTRAINT core_partner_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.core_partner OWNER TO postgres;

--
-- Name: core_partner_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_partner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_partner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_promotion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_promotion (
    id bigint NOT NULL,
    year integer NOT NULL,
    name character varying(200) NOT NULL,
    photo character varying(100) NOT NULL,
    description text NOT NULL,
    CONSTRAINT core_promotion_year_check CHECK ((year >= 0))
);


ALTER TABLE public.core_promotion OWNER TO postgres;

--
-- Name: core_promotion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_promotion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_promotion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_sitestats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_sitestats (
    id bigint NOT NULL,
    members_count integer NOT NULL,
    countries_count integer NOT NULL,
    promotions_count integer NOT NULL,
    insertion_rate integer NOT NULL,
    CONSTRAINT core_sitestats_countries_count_check CHECK ((countries_count >= 0)),
    CONSTRAINT core_sitestats_insertion_rate_check CHECK ((insertion_rate >= 0)),
    CONSTRAINT core_sitestats_members_count_check CHECK ((members_count >= 0)),
    CONSTRAINT core_sitestats_promotions_count_check CHECK ((promotions_count >= 0))
);


ALTER TABLE public.core_sitestats OWNER TO postgres;

--
-- Name: core_sitestats_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_sitestats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_sitestats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_testimonial; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_testimonial (
    id bigint NOT NULL,
    content text NOT NULL,
    is_featured boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    member_id bigint NOT NULL
);


ALTER TABLE public.core_testimonial OWNER TO postgres;

--
-- Name: core_testimonial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_testimonial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_testimonial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO postgres;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO postgres;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Message	9	add_contactmessage
22	Can change Message	9	change_contactmessage
23	Can delete Message	9	delete_contactmessage
24	Can view Message	9	view_contactmessage
25	Can add Événement	10	add_event
26	Can change Événement	10	change_event
27	Can delete Événement	10	delete_event
28	Can view Événement	10	view_event
29	Can add Partenaire	18	add_partner
30	Can change Partenaire	18	change_partner
31	Can delete Partenaire	18	delete_partner
32	Can view Partenaire	18	view_partner
33	Can add Statistiques du site	20	add_sitestats
34	Can change Statistiques du site	20	change_sitestats
35	Can delete Statistiques du site	20	delete_sitestats
36	Can view Statistiques du site	20	view_sitestats
37	Can add Membre	15	add_member
38	Can change Membre	15	change_member
39	Can delete Membre	15	delete_member
40	Can view Membre	15	view_member
41	Can add Photo	13	add_galleryimage
42	Can change Photo	13	change_galleryimage
43	Can delete Photo	13	delete_galleryimage
44	Can view Photo	13	view_galleryimage
45	Can add Article	16	add_newsarticle
46	Can change Article	16	change_newsarticle
47	Can delete Article	16	delete_newsarticle
48	Can view Article	16	view_newsarticle
49	Can add Témoignage	21	add_testimonial
50	Can change Témoignage	21	change_testimonial
51	Can delete Témoignage	21	delete_testimonial
52	Can view Témoignage	21	view_testimonial
53	Can add Promotion	19	add_promotion
54	Can change Promotion	19	change_promotion
55	Can delete Promotion	19	delete_promotion
56	Can view Promotion	19	view_promotion
57	Can add Activité	6	add_activity
58	Can change Activité	6	change_activity
59	Can delete Activité	6	delete_activity
60	Can view Activité	6	view_activity
61	Can add Infos de l'association	7	add_associationinfo
62	Can change Infos de l'association	7	change_associationinfo
63	Can delete Infos de l'association	7	delete_associationinfo
64	Can view Infos de l'association	7	view_associationinfo
65	Can add FAQ	11	add_faq
66	Can change FAQ	11	change_faq
67	Can delete FAQ	11	delete_faq
68	Can view FAQ	11	view_faq
69	Can add Membre du bureau	8	add_bureaumember
70	Can change Membre du bureau	8	change_bureaumember
71	Can delete Membre du bureau	8	delete_bureaumember
72	Can view Membre du bureau	8	view_bureaumember
73	Can add Offre d'emploi	14	add_joboffer
74	Can change Offre d'emploi	14	change_joboffer
75	Can delete Offre d'emploi	14	delete_joboffer
76	Can view Offre d'emploi	14	view_joboffer
77	Can add Abonné newsletter	17	add_newslettersubscriber
78	Can change Abonné newsletter	17	change_newslettersubscriber
79	Can delete Abonné newsletter	17	delete_newslettersubscriber
80	Can view Abonné newsletter	17	view_newslettersubscriber
81	Can add Album	12	add_galleryalbum
82	Can change Album	12	change_galleryalbum
83	Can delete Album	12	delete_galleryalbum
84	Can view Album	12	view_galleryalbum
85	Can add Document	23	add_memberdocument
86	Can change Document	23	change_memberdocument
87	Can delete Document	23	delete_memberdocument
88	Can view Document	23	view_memberdocument
89	Can add Notification	24	add_notification
90	Can change Notification	24	change_notification
91	Can delete Notification	24	delete_notification
92	Can view Notification	24	view_notification
93	Can add Paiement de cotisation	22	add_cotisationpayment
94	Can change Paiement de cotisation	22	change_cotisationpayment
95	Can delete Paiement de cotisation	22	delete_cotisationpayment
96	Can view Paiement de cotisation	22	view_cotisationpayment
97	Can add Blacklisted Token	25	add_blacklistedtoken
98	Can change Blacklisted Token	25	change_blacklistedtoken
99	Can delete Blacklisted Token	25	delete_blacklistedtoken
100	Can view Blacklisted Token	25	view_blacklistedtoken
101	Can add Outstanding Token	26	add_outstandingtoken
102	Can change Outstanding Token	26	change_outstandingtoken
103	Can delete Outstanding Token	26	delete_outstandingtoken
104	Can view Outstanding Token	26	view_outstandingtoken
\.


--
-- Data for Name: core_activity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_activity (id, title, description, quarter, year, date_label, status, "order") FROM stdin;
1	Assemblée Générale Ordinaire	Bilan de l'année écoulée, adoption du budget prévisionnel et renouvellement partiel du bureau.	Q1	2026	Janvier 2026	done	0
2	Campagne d'adhésion	Lancement de la campagne annuelle de recrutement de nouveaux membres. Objectif : 100 nouveaux adhérents.	Q1	2026	Février 2026	done	1
3	Journée portes ouvertes au lycée	Visite du Lycée HOUPHOUËT-BOIGNY de Korhogo avec les anciens. Échanges avec les élèves actuels.	Q1	2026	Mars 2026	done	2
4	Programme de mentorat — Cohorte 2	Lancement de la deuxième cohorte de mentorat. Jumelage de 30 jeunes diplômés avec des aînés.	Q2	2026	Avril 2026	in-progress	0
5	Forum Emploi & Insertion	Salon professionnel réservé aux membres. Stands d'entreprises partenaires, ateliers CV.	Q2	2026	Mai 2026	upcoming	1
6	Dîner Gala Annuel	Soirée de gala réunissant toutes les générations. Remise de prix d'excellence et levée de fonds.	Q2	2026	Juin 2026	upcoming	2
7	Tournoi sportif inter-promotions	Compétitions de football, basketball et athlétisme entre promotions.	Q3	2026	Juillet 2026	upcoming	0
8	Action solidaire — Rentrée scolaire	Distribution de kits scolaires, bourses d'études et rénovation d'une salle de classe.	Q3	2026	Septembre 2026	upcoming	1
9	Retrouvailles promotions 2000-2010	Week-end dédié aux promotions 2000 à 2010. Visite du lycée et soirée de retrouvailles.	Q3	2026	Septembre 2026	upcoming	2
10	Conférence annuelle	Conférence thématique ouverte au public. Intervenants : anciens élèves leaders.	Q4	2026	Octobre 2026	upcoming	0
11	Expansion diaspora	Création des antennes 2ALHB à Paris, Dakar et Casablanca.	Q4	2026	Novembre 2026	upcoming	1
12	Bilan annuel & Fête de fin d'année	Présentation du bilan, célébration des réussites et lancement du plan 2027.	Q4	2026	Décembre 2026	upcoming	2
\.


--
-- Data for Name: core_associationinfo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_associationinfo (id, name, full_name, slogan, email, phone, address, facebook_url, linkedin_url, adhesion_fee, monthly_fee, annual_fee, whatsapp) FROM stdin;
1	2ALHB	Amicale des Anciens du Lycée HOUPHOUËT-BOIGNY de Korhogo	Connecter les anciens, inspirer les générations futures	contact@2alhb.com	+225 07 02 00 00 00	Korhogo			5000	5000	60000	+33695841639
\.


--
-- Data for Name: core_bureaumember; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_bureaumember (id, name, role, category, photo, "order", member_id) FROM stdin;
18	SORHO Fougnigué Mohamed	Président	direction		0	\N
19	COULIBALY Tchanga Guy Roland Kévin	Vice-Président	direction		1	\N
20	OUATTARA Kahafoa Désiré	Secrétaire Général	direction		2	\N
21	DIARRASSOUBA Dognimin Drissa	Trésorier	direction		3	\N
22	TUO Nawa Moise	Commissaire Aux Comptes	direction		4	\N
\.


--
-- Data for Name: core_contactmessage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_contactmessage (id, name, email, subject, message, is_read, created_at) FROM stdin;
\.


--
-- Data for Name: core_cotisationpayment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_cotisationpayment (id, amount, period_label, payment_method, reference, paid_at, created_at, member_id) FROM stdin;
\.


--
-- Data for Name: core_event; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_event (id, title, description, date, location, image, is_published, created_at, category, is_featured) FROM stdin;
\.


--
-- Data for Name: core_faq; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_faq (id, question, answer, "order", is_published) FROM stdin;
1	Qui peut adhérer à la 2ALHB ?	Tout ancien élève du Lycée HOUPHOUËT-BOIGNY de Korhogo, quelle que soit sa promotion ou son lieu de résidence actuel, peut demander à adhérer à l'amicale.	0	t
2	L'adhésion est-elle payante ?	Le droit d'adhésion est de 5 000 FCFA. Les membres adhérents paient en plus une cotisation mensuelle (5 000 FCFA) ou annuelle (60 000 FCFA).	1	t
3	Comment se déroule la validation ?	Après soumission du formulaire, le bureau exécutif examine votre demande. Vous recevez une confirmation par email sous 48h.	2	t
4	Quels sont les avantages d'être membre ?	Accès à l'annuaire des anciens, invitations aux événements exclusifs, programmes de mentorat, partage d'opportunités professionnelles.	3	t
5	Je suis à l'étranger, puis-je participer ?	Absolument ! La 2ALHB a des membres dans plusieurs pays. Vous pouvez participer aux événements en ligne et rejoindre les groupes de la diaspora.	4	t
6	Comment puis-je m'impliquer davantage ?	Vous pouvez rejoindre une commission, proposer des événements ou devenir mentor pour les jeunes diplômés. Contactez le bureau pour en savoir plus.	5	t
\.


--
-- Data for Name: core_galleryalbum; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_galleryalbum (id, title, description, cover_image, is_published, created_at, event_id) FROM stdin;
\.


--
-- Data for Name: core_galleryimage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_galleryimage (id, title, image, caption, created_at, event_id, album_id) FROM stdin;
\.


--
-- Data for Name: core_joboffer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_joboffer (id, title, company, location, job_type, sector, description, apply_url, poster_name, poster_email, is_active, created_at, posted_by_id) FROM stdin;
\.


--
-- Data for Name: core_member; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_member (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, phone, promotion_id, profession, company, city, country, bio, photo, linkedin, is_approved, created_at, updated_at, cotisation_mode, membership_type, member_number) FROM stdin;
1	pbkdf2_sha256$1200000$PRDaFSVnp0qssueXrSDnB5$fUsmWesYvYJh5dbVR27k30ldXvMV9l0QYgDP3byiHww=	2026-04-29 09:44:25.971514+01	t	admin	Admin	2ALHB	admin@2alhb.ci	t	t	2026-04-28 15:32:19+01		\N	Administrateur			Côte d'Ivoire				t	2026-04-28 15:32:20.997061+01	2026-04-29 09:20:34.05866+01		adherent	2ALHB-0000-001
\.


--
-- Data for Name: core_member_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_member_groups (id, member_id, group_id) FROM stdin;
\.


--
-- Data for Name: core_member_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_member_user_permissions (id, member_id, permission_id) FROM stdin;
\.


--
-- Data for Name: core_memberdocument; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_memberdocument (id, title, category, file, description, is_adherent_only, published_at, created_at) FROM stdin;
\.


--
-- Data for Name: core_newsarticle; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_newsarticle (id, title, slug, excerpt, content, image, is_published, published_at, author_id) FROM stdin;
\.


--
-- Data for Name: core_newslettersubscriber; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_newslettersubscriber (id, email, is_active, subscribed_at) FROM stdin;
\.


--
-- Data for Name: core_notification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_notification (id, title, message, notification_type, is_read, link, created_at, recipient_id) FROM stdin;
\.


--
-- Data for Name: core_partner; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_partner (id, name, logo, website, "order") FROM stdin;
\.


--
-- Data for Name: core_promotion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_promotion (id, year, name, photo, description) FROM stdin;
\.


--
-- Data for Name: core_sitestats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_sitestats (id, members_count, countries_count, promotions_count, insertion_rate) FROM stdin;
1	500	8	40	85
\.


--
-- Data for Name: core_testimonial; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_testimonial (id, content, is_featured, created_at, member_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-04-28 23:39:09.752903+01	1	Admin 2ALHB (?)	2	[{"changed": {"fields": ["Type de membre"]}}]	15	1
2	2026-04-28 23:39:15.95425+01	1	Admin 2ALHB (?)	2	[{"changed": {"fields": ["Approuv\\u00e9"]}}]	15	1
3	2026-04-29 00:01:43.708684+01	1	[Autre document] Statut	1	[{"added": {}}]	23	1
4	2026-04-29 00:02:47.701656+01	1	[Autre document] Statut	3		23	1
5	2026-04-29 00:03:26.56019+01	1	Nouveau document : Statut → Admin 2ALHB	3		24	1
6	2026-04-29 00:18:30.211888+01	1	2ALHB	2	[{"changed": {"fields": ["Email", "Adresse"]}}]	7	1
7	2026-04-29 00:41:12.700736+01	1	2ALHB	2	[{"changed": {"fields": ["WhatsApp"]}}]	7	1
8	2026-04-29 09:54:37.59289+01	1	2ALHB	2	[{"changed": {"fields": ["T\\u00e9l\\u00e9phone"]}}]	7	1
9	2026-04-29 09:56:10.252678+01	1	2ALHB	2	[{"changed": {"fields": ["Adresse"]}}]	7	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	core	activity
7	core	associationinfo
8	core	bureaumember
9	core	contactmessage
10	core	event
11	core	faq
12	core	galleryalbum
13	core	galleryimage
14	core	joboffer
15	core	member
16	core	newsarticle
17	core	newslettersubscriber
18	core	partner
19	core	promotion
20	core	sitestats
21	core	testimonial
22	core	cotisationpayment
23	core	memberdocument
24	core	notification
25	token_blacklist	blacklistedtoken
26	token_blacklist	outstandingtoken
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-28 15:31:12.167919+01
2	contenttypes	0002_remove_content_type_name	2026-04-28 15:31:12.177391+01
3	auth	0001_initial	2026-04-28 15:31:12.210995+01
4	auth	0002_alter_permission_name_max_length	2026-04-28 15:31:12.216048+01
5	auth	0003_alter_user_email_max_length	2026-04-28 15:31:12.221428+01
6	auth	0004_alter_user_username_opts	2026-04-28 15:31:12.227348+01
7	auth	0005_alter_user_last_login_null	2026-04-28 15:31:12.233062+01
8	auth	0006_require_contenttypes_0002	2026-04-28 15:31:12.234419+01
9	auth	0007_alter_validators_add_error_messages	2026-04-28 15:31:12.23996+01
10	auth	0008_alter_user_username_max_length	2026-04-28 15:31:12.245991+01
11	auth	0009_alter_user_last_name_max_length	2026-04-28 15:31:12.251605+01
12	auth	0010_alter_group_name_max_length	2026-04-28 15:31:12.258559+01
13	auth	0011_update_proxy_permissions	2026-04-28 15:31:12.26589+01
14	auth	0012_alter_user_first_name_max_length	2026-04-28 15:31:12.271093+01
15	core	0001_initial	2026-04-28 15:31:12.361271+01
16	admin	0001_initial	2026-04-28 15:31:12.381869+01
17	admin	0002_logentry_remove_auto_add	2026-04-28 15:31:12.392709+01
18	admin	0003_logentry_add_action_flag_choices	2026-04-28 15:31:12.405673+01
19	core	0002_promotion_alter_member_promotion	2026-04-28 15:31:12.433303+01
20	core	0003_member_cotisation_mode_member_membership_type	2026-04-28 15:31:12.461255+01
21	core	0004_activity_associationinfo_faq_event_category_and_more	2026-04-28 15:31:12.533451+01
22	core	0005_newslettersubscriber_galleryalbum_galleryimage_album	2026-04-28 15:31:12.556139+01
23	sessions	0001_initial	2026-04-28 15:31:12.563561+01
24	core	0006_memberdocument_cotisationpayment_notification	2026-04-28 23:26:22.51675+01
25	core	0007_associationinfo_whatsapp	2026-04-29 00:38:21.628762+01
26	core	0008_member_member_number	2026-04-29 09:17:25.762838+01
27	token_blacklist	0001_initial	2026-04-29 10:14:56.661367+01
28	token_blacklist	0002_outstandingtoken_jti_hex	2026-04-29 10:14:56.67875+01
29	token_blacklist	0003_auto_20171017_2007	2026-04-29 10:14:56.707496+01
30	token_blacklist	0004_auto_20171017_2013	2026-04-29 10:14:56.728714+01
31	token_blacklist	0005_remove_outstandingtoken_jti	2026-04-29 10:14:56.746007+01
32	token_blacklist	0006_auto_20171017_2113	2026-04-29 10:14:56.763777+01
33	token_blacklist	0007_auto_20171017_2214	2026-04-29 10:14:56.899285+01
34	token_blacklist	0008_migrate_to_bigautofield	2026-04-29 10:14:56.963466+01
35	token_blacklist	0010_fix_migrate_to_bigautofield	2026-04-29 10:14:56.991216+01
36	token_blacklist	0011_linearizes_history	2026-04-29 10:14:56.99277+01
37	token_blacklist	0012_alter_outstandingtoken_user	2026-04-29 10:14:57.010757+01
38	token_blacklist	0013_alter_blacklistedtoken_options_and_more	2026-04-29 10:14:57.031134+01
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
v4gcrxn0f6b5mjihi12bodkyuzi5jfby	.eJxVjDsOwjAQBe_iGllx1p-Ykj5nsNbeNQ4gR4qTCnF3EikFtDPz3lsE3NYStsZLmEhchRKXXxYxPbkegh5Y77NMc12XKcojkadtcpyJX7ez_Tso2Mq-7jlHD0ZZzAOo6LN1DkA748mYzuREltHYPiJ46PSOWYNSA1q2RFqLzxfRETdU:1wI0Wv:cqWSXEz8d2Gi-IpX2-39wYsSdKvEgUVfzgtJsT9B6HI	2026-05-13 09:44:25.973524+01
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 104, true);


--
-- Name: core_activity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_activity_id_seq', 12, true);


--
-- Name: core_associationinfo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_associationinfo_id_seq', 1, false);


--
-- Name: core_bureaumember_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_bureaumember_id_seq', 22, true);


--
-- Name: core_contactmessage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_contactmessage_id_seq', 1, false);


--
-- Name: core_cotisationpayment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_cotisationpayment_id_seq', 1, false);


--
-- Name: core_event_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_event_id_seq', 1, false);


--
-- Name: core_faq_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_faq_id_seq', 6, true);


--
-- Name: core_galleryalbum_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_galleryalbum_id_seq', 1, false);


--
-- Name: core_galleryimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_galleryimage_id_seq', 1, false);


--
-- Name: core_joboffer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_joboffer_id_seq', 1, false);


--
-- Name: core_member_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_member_groups_id_seq', 1, false);


--
-- Name: core_member_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_member_id_seq', 1, true);


--
-- Name: core_member_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_member_user_permissions_id_seq', 1, false);


--
-- Name: core_memberdocument_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_memberdocument_id_seq', 1, true);


--
-- Name: core_newsarticle_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_newsarticle_id_seq', 1, false);


--
-- Name: core_newslettersubscriber_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_newslettersubscriber_id_seq', 1, false);


--
-- Name: core_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_notification_id_seq', 1, true);


--
-- Name: core_partner_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_partner_id_seq', 1, false);


--
-- Name: core_promotion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_promotion_id_seq', 1, false);


--
-- Name: core_sitestats_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_sitestats_id_seq', 1, false);


--
-- Name: core_testimonial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_testimonial_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 9, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 26, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 38, true);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 1, false);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: core_activity core_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_activity
    ADD CONSTRAINT core_activity_pkey PRIMARY KEY (id);


--
-- Name: core_associationinfo core_associationinfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_associationinfo
    ADD CONSTRAINT core_associationinfo_pkey PRIMARY KEY (id);


--
-- Name: core_bureaumember core_bureaumember_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_bureaumember
    ADD CONSTRAINT core_bureaumember_pkey PRIMARY KEY (id);


--
-- Name: core_contactmessage core_contactmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_contactmessage
    ADD CONSTRAINT core_contactmessage_pkey PRIMARY KEY (id);


--
-- Name: core_cotisationpayment core_cotisationpayment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_cotisationpayment
    ADD CONSTRAINT core_cotisationpayment_pkey PRIMARY KEY (id);


--
-- Name: core_event core_event_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_event
    ADD CONSTRAINT core_event_pkey PRIMARY KEY (id);


--
-- Name: core_faq core_faq_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_faq
    ADD CONSTRAINT core_faq_pkey PRIMARY KEY (id);


--
-- Name: core_galleryalbum core_galleryalbum_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_galleryalbum
    ADD CONSTRAINT core_galleryalbum_pkey PRIMARY KEY (id);


--
-- Name: core_galleryimage core_galleryimage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_galleryimage
    ADD CONSTRAINT core_galleryimage_pkey PRIMARY KEY (id);


--
-- Name: core_joboffer core_joboffer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_joboffer
    ADD CONSTRAINT core_joboffer_pkey PRIMARY KEY (id);


--
-- Name: core_member_groups core_member_groups_member_id_group_id_cc728332_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_member_groups
    ADD CONSTRAINT core_member_groups_member_id_group_id_cc728332_uniq UNIQUE (member_id, group_id);


--
-- Name: core_member_groups core_member_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_member_groups
    ADD CONSTRAINT core_member_groups_pkey PRIMARY KEY (id);


--
-- Name: core_member core_member_member_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_member
    ADD CONSTRAINT core_member_member_number_key UNIQUE (member_number);


--
-- Name: core_member core_member_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_member
    ADD CONSTRAINT core_member_pkey PRIMARY KEY (id);


--
-- Name: core_member_user_permissions core_member_user_permiss_member_id_permission_id_b6f65267_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_member_user_permissions
    ADD CONSTRAINT core_member_user_permiss_member_id_permission_id_b6f65267_uniq UNIQUE (member_id, permission_id);


--
-- Name: core_member_user_permissions core_member_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_member_user_permissions
    ADD CONSTRAINT core_member_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: core_member core_member_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_member
    ADD CONSTRAINT core_member_username_key UNIQUE (username);


--
-- Name: core_memberdocument core_memberdocument_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_memberdocument
    ADD CONSTRAINT core_memberdocument_pkey PRIMARY KEY (id);


--
-- Name: core_newsarticle core_newsarticle_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_newsarticle
    ADD CONSTRAINT core_newsarticle_pkey PRIMARY KEY (id);


--
-- Name: core_newsarticle core_newsarticle_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_newsarticle
    ADD CONSTRAINT core_newsarticle_slug_key UNIQUE (slug);


--
-- Name: core_newslettersubscriber core_newslettersubscriber_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_newslettersubscriber
    ADD CONSTRAINT core_newslettersubscriber_email_key UNIQUE (email);


--
-- Name: core_newslettersubscriber core_newslettersubscriber_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_newslettersubscriber
    ADD CONSTRAINT core_newslettersubscriber_pkey PRIMARY KEY (id);


--
-- Name: core_notification core_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_notification
    ADD CONSTRAINT core_notification_pkey PRIMARY KEY (id);


--
-- Name: core_partner core_partner_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_partner
    ADD CONSTRAINT core_partner_pkey PRIMARY KEY (id);


--
-- Name: core_promotion core_promotion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_promotion
    ADD CONSTRAINT core_promotion_pkey PRIMARY KEY (id);


--
-- Name: core_promotion core_promotion_year_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_promotion
    ADD CONSTRAINT core_promotion_year_key UNIQUE (year);


--
-- Name: core_sitestats core_sitestats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_sitestats
    ADD CONSTRAINT core_sitestats_pkey PRIMARY KEY (id);


--
-- Name: core_testimonial core_testimonial_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_testimonial
    ADD CONSTRAINT core_testimonial_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: core_bureaumember_member_id_089cc660; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_bureaumember_member_id_089cc660 ON public.core_bureaumember USING btree (member_id);


--
-- Name: core_cotisationpayment_member_id_0987abbb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_cotisationpayment_member_id_0987abbb ON public.core_cotisationpayment USING btree (member_id);


--
-- Name: core_galleryalbum_event_id_9e7563e8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_galleryalbum_event_id_9e7563e8 ON public.core_galleryalbum USING btree (event_id);


--
-- Name: core_galleryimage_album_id_028d50c6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_galleryimage_album_id_028d50c6 ON public.core_galleryimage USING btree (album_id);


--
-- Name: core_galleryimage_event_id_e4370f38; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_galleryimage_event_id_e4370f38 ON public.core_galleryimage USING btree (event_id);


--
-- Name: core_joboffer_posted_by_id_76be8370; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_joboffer_posted_by_id_76be8370 ON public.core_joboffer USING btree (posted_by_id);


--
-- Name: core_member_groups_group_id_ed99774b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_member_groups_group_id_ed99774b ON public.core_member_groups USING btree (group_id);


--
-- Name: core_member_groups_member_id_4044d690; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_member_groups_member_id_4044d690 ON public.core_member_groups USING btree (member_id);


--
-- Name: core_member_member_number_a0d32832_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_member_member_number_a0d32832_like ON public.core_member USING btree (member_number varchar_pattern_ops);


--
-- Name: core_member_promotion_id_c5e1c7b8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_member_promotion_id_c5e1c7b8 ON public.core_member USING btree (promotion_id);


--
-- Name: core_member_user_permissions_member_id_cccf5977; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_member_user_permissions_member_id_cccf5977 ON public.core_member_user_permissions USING btree (member_id);


--
-- Name: core_member_user_permissions_permission_id_195d4d4a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_member_user_permissions_permission_id_195d4d4a ON public.core_member_user_permissions USING btree (permission_id);


--
-- Name: core_member_username_19950dbb_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_member_username_19950dbb_like ON public.core_member USING btree (username varchar_pattern_ops);


--
-- Name: core_newsarticle_author_id_0eb60244; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_newsarticle_author_id_0eb60244 ON public.core_newsarticle USING btree (author_id);


--
-- Name: core_newsarticle_slug_89eec238_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_newsarticle_slug_89eec238_like ON public.core_newsarticle USING btree (slug varchar_pattern_ops);


--
-- Name: core_newslettersubscriber_email_c9d9dbd8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_newslettersubscriber_email_c9d9dbd8_like ON public.core_newslettersubscriber USING btree (email varchar_pattern_ops);


--
-- Name: core_notification_recipient_id_24a3d95c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_notification_recipient_id_24a3d95c ON public.core_notification USING btree (recipient_id);


--
-- Name: core_testimonial_member_id_1b9fe00a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_testimonial_member_id_1b9fe00a ON public.core_testimonial USING btree (member_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_bureaumember core_bureaumember_member_id_089cc660_fk_core_member_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_bureaumember
    ADD CONSTRAINT core_bureaumember_member_id_089cc660_fk_core_member_id FOREIGN KEY (member_id) REFERENCES public.core_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_cotisationpayment core_cotisationpayment_member_id_0987abbb_fk_core_member_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_cotisationpayment
    ADD CONSTRAINT core_cotisationpayment_member_id_0987abbb_fk_core_member_id FOREIGN KEY (member_id) REFERENCES public.core_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_galleryalbum core_galleryalbum_event_id_9e7563e8_fk_core_event_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_galleryalbum
    ADD CONSTRAINT core_galleryalbum_event_id_9e7563e8_fk_core_event_id FOREIGN KEY (event_id) REFERENCES public.core_event(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_galleryimage core_galleryimage_album_id_028d50c6_fk_core_galleryalbum_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_galleryimage
    ADD CONSTRAINT core_galleryimage_album_id_028d50c6_fk_core_galleryalbum_id FOREIGN KEY (album_id) REFERENCES public.core_galleryalbum(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_galleryimage core_galleryimage_event_id_e4370f38_fk_core_event_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_galleryimage
    ADD CONSTRAINT core_galleryimage_event_id_e4370f38_fk_core_event_id FOREIGN KEY (event_id) REFERENCES public.core_event(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_joboffer core_joboffer_posted_by_id_76be8370_fk_core_member_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_joboffer
    ADD CONSTRAINT core_joboffer_posted_by_id_76be8370_fk_core_member_id FOREIGN KEY (posted_by_id) REFERENCES public.core_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_member_groups core_member_groups_group_id_ed99774b_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_member_groups
    ADD CONSTRAINT core_member_groups_group_id_ed99774b_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_member_groups core_member_groups_member_id_4044d690_fk_core_member_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_member_groups
    ADD CONSTRAINT core_member_groups_member_id_4044d690_fk_core_member_id FOREIGN KEY (member_id) REFERENCES public.core_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_member core_member_promotion_id_c5e1c7b8_fk_core_promotion_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_member
    ADD CONSTRAINT core_member_promotion_id_c5e1c7b8_fk_core_promotion_id FOREIGN KEY (promotion_id) REFERENCES public.core_promotion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_member_user_permissions core_member_user_per_member_id_cccf5977_fk_core_memb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_member_user_permissions
    ADD CONSTRAINT core_member_user_per_member_id_cccf5977_fk_core_memb FOREIGN KEY (member_id) REFERENCES public.core_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_member_user_permissions core_member_user_per_permission_id_195d4d4a_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_member_user_permissions
    ADD CONSTRAINT core_member_user_per_permission_id_195d4d4a_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_newsarticle core_newsarticle_author_id_0eb60244_fk_core_member_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_newsarticle
    ADD CONSTRAINT core_newsarticle_author_id_0eb60244_fk_core_member_id FOREIGN KEY (author_id) REFERENCES public.core_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_notification core_notification_recipient_id_24a3d95c_fk_core_member_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_notification
    ADD CONSTRAINT core_notification_recipient_id_24a3d95c_fk_core_member_id FOREIGN KEY (recipient_id) REFERENCES public.core_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_testimonial core_testimonial_member_id_1b9fe00a_fk_core_member_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_testimonial
    ADD CONSTRAINT core_testimonial_member_id_1b9fe00a_fk_core_member_id FOREIGN KEY (member_id) REFERENCES public.core_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_core_member_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_core_member_id FOREIGN KEY (user_id) REFERENCES public.core_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_core_memb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_core_memb FOREIGN KEY (user_id) REFERENCES public.core_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict ZE4R1WTCt2TkQi18qIldI2hSW9z5pTRLEjzyPxoOBm0tXGx7b3Zv2cAFV7HBcnV

