# Generated by Django 6.0.4 on 2026-04-24 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(unique=True, verbose_name="Année"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Les Invincibles",
                        max_length=200,
                        verbose_name="Nom de baptême",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to="promotions/",
                        verbose_name="Photo de groupe",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Promotion",
                "verbose_name_plural": "Promotions",
                "ordering": ["-year"],
            },
        ),
        migrations.AlterField(
            model_name="member",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="core.promotion",
                verbose_name="Promotion",
            ),
        ),
    ]
