# Generated by Django 6.0.4 on 2026-04-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_promotion_alter_member_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="cotisation_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mensuelle", "Mensuelle — 5 000 FCFA/mois"),
                    ("annuelle", "Annuelle — 60 000 FCFA/an"),
                ],
                help_text="Requis pour les membres adhérents",
                max_length=10,
                verbose_name="Mode de cotisation",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="membership_type",
            field=models.CharField(
                choices=[("simple", "Membre Simple"), ("adherent", "Membre Adhérent")],
                default="simple",
                max_length=10,
                verbose_name="Type de membre",
            ),
        ),
    ]
