# Generated by Django 6.0.4 on 2026-04-28 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_member_cotisation_mode_member_membership_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("Q1", "1er Trimestre"),
                            ("Q2", "2e Trimestre"),
                            ("Q3", "3e Trimestre"),
                            ("Q4", "4e Trimestre"),
                        ],
                        max_length=2,
                        verbose_name="Trimestre",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(default=2026, verbose_name="Année"),
                ),
                (
                    "date_label",
                    models.CharField(
                        help_text="Ex: Janvier 2026",
                        max_length=50,
                        verbose_name="Date affichée",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "Réalisé"),
                            ("in-progress", "En cours"),
                            ("upcoming", "À venir"),
                        ],
                        default="upcoming",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
            ],
            options={
                "verbose_name": "Activité",
                "verbose_name_plural": "Plan d'activités",
                "ordering": ["year", "quarter", "order"],
            },
        ),
        migrations.CreateModel(
            name="AssociationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="2ALHB", max_length=200, verbose_name="Nom"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        default="Amicale des Anciens du Lycée HOUPHOUËT-BOIGNY de Korhogo",
                        max_length=300,
                        verbose_name="Nom complet",
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        default="Connecter les anciens, inspirer les générations futures",
                        max_length=300,
                        verbose_name="Slogan",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="contact@2alhb.ci", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="+225 07 00 00 00 00",
                        max_length=20,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        default="Lycée HOUPHOUËT-BOIGNY de Korhogo\nCôte d'Ivoire",
                        verbose_name="Adresse",
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                (
                    "adhesion_fee",
                    models.PositiveIntegerField(
                        default=5000, verbose_name="Droit d'adhésion (FCFA)"
                    ),
                ),
                (
                    "monthly_fee",
                    models.PositiveIntegerField(
                        default=5000, verbose_name="Cotisation mensuelle (FCFA)"
                    ),
                ),
                (
                    "annual_fee",
                    models.PositiveIntegerField(
                        default=60000, verbose_name="Cotisation annuelle (FCFA)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Infos de l'association",
                "verbose_name_plural": "Infos de l'association",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Réponse")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("gala", "Gala"),
                    ("sport", "Sport"),
                    ("forum", "Forum"),
                    ("retrouvailles", "Retrouvailles"),
                    ("solidarite", "Solidarité"),
                    ("autre", "Autre"),
                ],
                default="autre",
                max_length=20,
                verbose_name="Catégorie",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Mis en avant"),
        ),
        migrations.AlterField(
            model_name="member",
            name="profession",
            field=models.CharField(max_length=200, verbose_name="Profession"),
        ),
        migrations.CreateModel(
            name="BureauMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Utilisé si pas lié à un membre",
                        max_length=200,
                        verbose_name="Nom complet",
                    ),
                ),
                ("role", models.CharField(max_length=200, verbose_name="Fonction")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("direction", "Direction"),
                            ("commission", "Commission"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="bureau/", verbose_name="Photo"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bureau_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre du bureau",
                "verbose_name_plural": "Membres du bureau",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Intitulé du poste"),
                ),
                (
                    "company",
                    models.CharField(max_length=200, verbose_name="Entreprise"),
                ),
                ("location", models.CharField(max_length=200, verbose_name="Lieu")),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("cdi", "CDI"),
                            ("cdd", "CDD"),
                            ("stage", "Stage"),
                            ("freelance", "Freelance"),
                        ],
                        max_length=10,
                        verbose_name="Type de contrat",
                    ),
                ),
                ("sector", models.CharField(max_length=100, verbose_name="Secteur")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "apply_url",
                    models.URLField(blank=True, verbose_name="Lien pour postuler"),
                ),
                (
                    "poster_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom du publieur"
                    ),
                ),
                (
                    "poster_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de contact"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_offers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Publié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre d'emploi",
                "verbose_name_plural": "Offres d'emploi",
                "ordering": ["-created_at"],
            },
        ),
    ]
