# Generated by Django 6.0.4 on 2026-04-28 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_activity_associationinfo_faq_event_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Abonné newsletter",
                "verbose_name_plural": "Abonnés newsletter",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to="gallery/covers/",
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="albums",
                        to="core.event",
                        verbose_name="Événement lié",
                    ),
                ),
            ],
            options={
                "verbose_name": "Album",
                "verbose_name_plural": "Albums",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="core.galleryalbum",
                verbose_name="Album",
            ),
        ),
    ]
