# Generated by Django 6.0.4 on 2026-04-28 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_newslettersubscriber_galleryalbum_galleryimage_album"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pv", "Procès-verbal d'AG"),
                            ("rapport", "Rapport financier"),
                            ("newsletter", "Newsletter"),
                            ("autre", "Autre document"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="documents/", verbose_name="Fichier"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_adherent_only",
                    models.BooleanField(
                        default=True, verbose_name="Réservé aux adhérents"
                    ),
                ),
                ("published_at", models.DateField(verbose_name="Date de publication")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="CotisationPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Montant (FCFA)")),
                (
                    "period_label",
                    models.CharField(
                        help_text="Ex: Avril 2026, Année 2026",
                        max_length=50,
                        verbose_name="Période",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Mode de paiement"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                ("paid_at", models.DateField(verbose_name="Date de paiement")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement de cotisation",
                "verbose_name_plural": "Paiements de cotisation",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("event", "Événement"),
                            ("job", "Offre d'emploi"),
                            ("cotisation", "Cotisation"),
                            ("document", "Document"),
                            ("general", "Général"),
                        ],
                        default="general",
                        max_length=15,
                        verbose_name="Type",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="URL relative vers la page concernée",
                        max_length=300,
                        verbose_name="Lien",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
