# Generated by Django 6.0.4 on 2026-04-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_memberdocument_cotisationpayment_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="associationinfo",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                help_text="Numéro avec indicatif, ex: +2250700000000",
                max_length=20,
                verbose_name="WhatsApp",
            ),
        ),
    ]
