# Generated by Django 6.0.4 on 2026-04-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_associationinfo_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="member_number",
            field=models.CharField(
                blank=True,
                help_text="Généré automatiquement : 2ALHB-PROMO-XXX",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Numéro d'adhérent",
            ),
        ),
    ]
