# Generated by Django 6.0.4 on 2026-05-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_member_member_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotisationpayment",
            name="category",
            field=models.CharField(
                choices=[
                    ("adhesion", "Droit d'adhésion"),
                    ("cotisation", "Cotisation"),
                ],
                default="cotisation",
                max_length=15,
                verbose_name="Catégorie",
            ),
        ),
    ]
