# Generated by Django 6.0.4 on 2026-05-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_cotisationpayment_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="associationinfo",
            name="welcome_email_body",
            field=models.TextField(
                default="Cher(e) {prenom},\n\nC'est avec un immense plaisir que nous vous accueillons au sein de la 2ALHB — l'Amicale des Anciens du Lycée HOUPHOUËT-BOIGNY de Korhogo.\n\nVous faites désormais partie d'un réseau solidaire de plus de 500 anciens élèves répartis dans 8 pays, unis par les valeurs d'entraide, d'excellence et de fraternité.\n\nN'hésitez pas à consulter l'annuaire des membres, participer aux événements et contribuer à la vie de l'amicale.\n\nFraternellement,\nLe Bureau de la 2ALHB",
                help_text="Variables disponibles : {prenom}, {nom}, {promotion}, {type_membre}. Ce message est envoyé en complément du mail technique contenant les identifiants.",
                verbose_name="Corps email d'accueil",
            ),
        ),
        migrations.AddField(
            model_name="associationinfo",
            name="welcome_email_subject",
            field=models.CharField(
                default="Bienvenue dans la grande famille 2ALHB !",
                help_text="Objet de l'email d'accueil envoyé en plus du mail technique avec les identifiants.",
                max_length=200,
                verbose_name="Objet email d'accueil",
            ),
        ),
    ]
