# Generated by Django 6.0.4 on 2026-08-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_add_welcome_email_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("statuts", "Statuts"),
                            ("reglement", "Règlement Intérieur"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Type de document",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Sous-titre"
                    ),
                ),
                ("preamble", models.TextField(blank=True, verbose_name="Préambule")),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=50, verbose_name="Version"
                    ),
                ),
                (
                    "adopted_date",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 20 avril 2026",
                        max_length=100,
                        verbose_name="Date d'adoption",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        upload_to="official_documents/",
                        verbose_name="Fichier PDF",
                    ),
                ),
                (
                    "section_label",
                    models.CharField(
                        default="Chapitre",
                        help_text="Ex: 'Chapitre' pour statuts, 'Titre' pour règlement",
                        max_length=50,
                        verbose_name="Nom des sections",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Texte affiché en bas avant le lien vers le document associé",
                        verbose_name="Note de bas de page",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document officiel",
                "verbose_name_plural": "Documents officiels",
                "ordering": ["document_type"],
            },
        ),
        migrations.CreateModel(
            name="OfficialDocumentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Numéro")),
                ("title", models.CharField(max_length=300, verbose_name="Titre")),
                (
                    "articles_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'articles"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.officialdocument",
                        verbose_name="Document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ["order", "number"],
                "unique_together": {("document", "number")},
            },
        ),
        migrations.CreateModel(
            name="OfficialDocumentArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu de l'article")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="core.officialdocumentsection",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["order"],
            },
        ),
    ]
